<?php
return [
    'colors' => ['red', 'orange', 'white', 'yellow', 'green', 'blue'],
    'faces' => [
        ['name' => 'front'],
        ['name' => 'back'],
        ['name' => 'top'],
        ['name' => 'bottom'],
        ['name' => 'left'],
        ['name' => 'right'],
    ],
    "cells" =>
        [
            [ "x_coordinate" => 1,"y_coordinate" => 1, "color" => "red"],
            [ "x_coordinate" => 1,"y_coordinate" => 2, "color" => "red"],
            [ "x_coordinate" => 1,"y_coordinate" => 3, "color" => "red"],
            [ "x_coordinate" => 2,"y_coordinate" => 1, "color" => "red"],
            [ "x_coordinate" => 2,"y_coordinate" => 2, "color" => "red"],
            [ "x_coordinate" => 2,"y_coordinate" => 3, "color" => "red"],
            [ "x_coordinate" => 3,"y_coordinate" => 1, "color" => "red"],
            [ "x_coordinate" => 3,"y_coordinate" => 2, "color" => "red"],
            [ "x_coordinate" => 3,"y_coordinate" => 3, "color" => "red"],
            [ "x_coordinate" => 4,"y_coordinate" => 1, "color" => "blue"],
            [ "x_coordinate" => 4,"y_coordinate" => 2, "color" => "blue"],
            [ "x_coordinate" => 4,"y_coordinate" => 3, "color" => "blue"],
            [ "x_coordinate" => 5,"y_coordinate" => 1, "color" => "blue"],
            [ "x_coordinate" => 5,"y_coordinate" => 2, "color" => "blue"],
            [ "x_coordinate" => 5,"y_coordinate" => 3, "color" => "blue"],
            [ "x_coordinate" => 6,"y_coordinate" => 1, "color" => "blue"],
            [ "x_coordinate" => 6,"y_coordinate" => 2, "color" => "blue"],
            [ "x_coordinate" => 6,"y_coordinate" => 3, "color" => "blue"],
            [ "x_coordinate" => 7,"y_coordinate" => 1, "color" => "yellow"],
            [ "x_coordinate" => 7,"y_coordinate" => 2, "color" => "yellow"],
            [ "x_coordinate" => 7,"y_coordinate" => 3, "color" => "yellow"],
            [ "x_coordinate" => 8,"y_coordinate" => 1, "color" => "yellow"],
            [ "x_coordinate" => 8,"y_coordinate" => 2, "color" => "yellow"],
            [ "x_coordinate" => 8,"y_coordinate" => 3, "color" => "yellow"],
            [ "x_coordinate" => 9,"y_coordinate" => 1, "color" => "yellow"],
            [ "x_coordinate" => 9,"y_coordinate" => 2, "color" => "yellow"],
            [ "x_coordinate" => 9,"y_coordinate" => 3, "color" => "yellow"],
            [ "x_coordinate" => 10,"y_coordinate" => 1, "color" => "white"],
            [ "x_coordinate" => 10,"y_coordinate" => 2, "color" => "white"],
            [ "x_coordinate" => 10,"y_coordinate" => 3, "color" => "white"],
            [ "x_coordinate" => 11,"y_coordinate" => 1, "color" => "white"],
            [ "x_coordinate" => 11,"y_coordinate" => 2, "color" => "white"],
            [ "x_coordinate" => 11,"y_coordinate" => 3, "color" => "white"],
            [ "x_coordinate" => 12,"y_coordinate" => 1, "color" => "white"],
            [ "x_coordinate" => 12,"y_coordinate" => 2, "color" => "white"],
            [ "x_coordinate" => 12,"y_coordinate" => 3, "color" => "white"],
            [ "x_coordinate" => 13,"y_coordinate" => 1, "color" => "green"],
            [ "x_coordinate" => 13,"y_coordinate" => 2, "color" => "green"],
            [ "x_coordinate" => 13,"y_coordinate" => 3, "color" => "green"],
            [ "x_coordinate" => 14,"y_coordinate" => 1, "color" => "green"],
            [ "x_coordinate" => 14,"y_coordinate" => 2, "color" => "green"],
            [ "x_coordinate" => 14,"y_coordinate" => 3, "color" => "green"],
            [ "x_coordinate" => 15,"y_coordinate" => 1, "color" => "green"],
            [ "x_coordinate" => 15,"y_coordinate" => 2, "color" => "green"],
            [ "x_coordinate" => 15,"y_coordinate" => 3, "color" => "green"],
            [ "x_coordinate" => 16,"y_coordinate" => 1, "color" => "blue"],
            [ "x_coordinate" => 16,"y_coordinate" => 2, "color" => "blue"],
            [ "x_coordinate" => 16,"y_coordinate" => 3, "color" => "blue"],
            [ "x_coordinate" => 17,"y_coordinate" => 1, "color" => "blue"],
            [ "x_coordinate" => 17,"y_coordinate" => 2, "color" => "blue"],
            [ "x_coordinate" => 17,"y_coordinate" => 3, "color" => "blue"],
            [ "x_coordinate" => 18,"y_coordinate" => 1, "color" => "blue"],
            [ "x_coordinate" => 18,"y_coordinate" => 1, "color" => "blue"],
            [ "x_coordinate" => 18,"y_coordinate" => 3, "color" => "blue"],
        ],
    "rotations" =>
        [
            'L', 'R', 'U', 'D', 'F', 'B'
        ]
];
